name = "iperf-me-mvp"
main = "src/worker.js"
compatibility_date = "2024-10-01"
workers_dev = true

# Attach the Worker to your zone and custom subdomain
routes = [
  { pattern = "edge.iperf.me/*", zone_name = "iperf.me" }
]

# wrangler.toml (wrangler v3.88.0^)
[observability]
enabled = false

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true