# worker/wrangler.toml
name = "iperf-me-mvp"
main = "src/worker.js"              # this matches your repo: worker/src/worker.js
compatibility_date = "2024-10-01"   # must NOT be in the future
workers_dev = true

# optional, but fine to keep
[placement]
mode = "smart"

# Route ONLY API paths to the worker so Pages/HTML never swallows them
# (this fixes the “/api/d returns HTML / 503” issue when Pages is present)
[[routes]]
pattern = "iperf.me/api/*"
zone_name = "iperf.me"

# Optional extra entrypoint for testing/bypassing Pages
# If you’ll only ever use the Worker for API calls, you can scope it to /api/* too:
# pattern = "edge.iperf.me/api/*"
[[routes]]
pattern = "edge.iperf.me/*"
zone_name = "iperf.me"

[observability]
enabled = false

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 1
