name: Deploy to Cloudflare
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # optional diagnostics
      - name: Show repo layout
        run: |
          node -v; npm -v
          ls -la; ls -la worker
          echo "---- wrangler.toml ----"
          cat worker/wrangler.toml

      - name: Publish Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          wranglerVersion: '4.42.0'   # keep or remove; both fine
          workingDirectory: worker
          command: deploy            # <-- was 'publish --verbose'